### ISSUE TITLE
Got game invite function

### ISSUE THREAD

**Issue by Hansbald** [SteamRE/Steam4NET#1]
I can't seem to be able to find a function that executes when you recieve a game invite

**Comment by voided** [comment]
I believe game invites are sent as chat messages, but as `EChatEntryType.k_EChatEntryTypeInviteGame`.

So you just need to listen for the `FriendChatMsg_t` callback and check for that chat entry type.

**Comment by Hansbald** [comment]
Ok but how I only see methods and no events that get trigert am I just stupid?

**Comment by voided** [comment]
See https://github.com/SteamRE/Steam4NET/blob/master/Steam4Test/Program.cs#L191 for how callbacks are handled. You'd want to be checking for `FriendChatMsg_t.k_iCallback`.

**Comment by Hansbald** [comment]
I already looked at that code but I think I miss something obvious:
while (Steamworks.GetCallback(pipe, ref callbackMsg)
This line starts a loop for the time Steamworks calls the API giving the output to the callbackMsg variable

Then I need to check if callbackMsg is EChatEntryType.k_EChatEntryTypeInviteGame

but callbackMsg is int and  EChatEntryType.k_EChatEntryTypeInviteGame is somethinh different?!

(Also how do I mark code like you did?)

**Comment by voided** [comment]
You need to convert `callbackMsg.m_pubParam` to `FriendChatMsg_t`, then you can check that object's `m_eChatEntryType`

**Comment by Hansbald** [comment]
I did that:
FriendChatMsg_t friendStatMsg = (FriendChatMsg_t)Marshal.PtrToStructure(callbackMsg.m_pubParam, typeof(FriendChatMsg_t));

However

friendStatMsg.m_eChatEntryType.Equals(EChatEntryType.k_EChatEntryTypeInviteGame)
and 
friendStatMsg.m_eChatEntryType == EChatEntryType.k_EChatEntryTypeInviteGame

Don't do anything at all

I also tried 
friendStatMsg.m_eChatEntryType.GetTypeCode

**Comment by Hansbald** [comment]
I tried everything I can think of now - nothing
